### PR TITLE
fix ip not displaying correctly w ipv4 | ipv6

### PR DESCRIPTION
**Pull request by d3mash**
hey so I noticed an issue with archey which displays an html string in IP line, check out my suggestion. 
it should work on all unix systems

### CODE REVIEW

**Comment by jskinne3** [comment]
I noticed the same problem and I'm glad you built such an elegant fix, @d3mash. I like archey and I want it to keep working. But, I notice that the last version released with homebrew was back in 2016. Are there plans to release another version, @obihann, or should we perhaps fork it if we want updates?

**Comment by djbeadle** [comment]
I'm going to shoot @obihann an email to make sure he sees this. :-)

**Comment by ericfitz** [comment]
d3mash' fix will get the IP from local configuration rather than from the outside.  This means that you won't see your actual public IP if you're behind NAT.

A simpler fix would be to change the URL that archey uses to get the IP address from.  The url in source is "4.ifcfg.me" (and 6.ifcfg.me for IPv6) - both these are offline.  The archey script that homebrew installs doesn't match either of these; the version in homebrew is going to the url "eth0.me" which appears to be offline and pointing to google but not doing a referral.

https://checkip.amazonaws.com should work just fine in place of the previous urls.

**Comment by djbeadle** [comment]
@ericfitz That's a good point-- both could be useful though, depending on your preferences. Does it make sense to use a flag to differentiate between the two options?

**Comment by d3mash** [comment]
closing this due to lack of feedback

**Pull request closed without merging**
