### PR TITLE
Feature custome logo

### PR DESCRIPTION
**Pull request by vladshub**
Added support for custom logo.
You can put the custom logo under $HOME/.config/archey-logo

### CODE REVIEW

**Comment by obihann** [comment]
@vladshub neat idea, why did you close the PR?

**Comment by vladshub** [comment]
@obihann we developed it internally and by "accident" put our logo as the main one. 
I'll have a pull request that has the regular logo as the main one soon :)

**Comment by obihann** [comment]
Awesome thanks!

**Comment by vigneshmarthandan** [comment]
Hi the custom logo looks like a neat feature. Can you please point me to few sample logos.

**Pull request closed without merging**
